### ISSUE TITLE
Tests failing

### ISSUE THREAD

**Issue by balasankarc** [resque/redis-namespace#112]
Hi, I have packaged redis-namespace for Debian. But now, some tests are failing. Can you help me fix them?
```
RUBYLIB=/home/balasankarc/packaging/trying/redis-namespace/ruby-redis-namespace/debian/ruby-redis-namespace/usr/lib/ruby/vendor_ruby:. rake2.2 -f debian/ruby-tests.rake
/usr/bin/ruby2.2 /usr/bin/rspec --pattern ./spec/\*\*/\*_spec.rb
....................................................................................FFFFFF......

Failures:

  1) redis redis 2.8 commands set scan methods #sscan when supplied :match should retrieve the matching set members from the proper set
     Failure/Error: expect(results).to match(matching_subset)
       expected ["zeta:two", "zeta:one"] to match ["zeta:one", "zeta:two"]
     # ./spec/redis_spec.rb:668:in `block (6 levels) in <top (required)>'

  2) redis redis 2.8 commands set scan methods #sscan without :match supplied should retrieve all set members from the proper set
     Failure/Error: expect(results).to match(set)
       expected ["three", "zeta:two", "zeta:one"] to match ["zeta:one", "zeta:two", "three"]
     # ./spec/redis_spec.rb:674:in `block (6 levels) in <top (required)>'

  3) redis redis 2.8 commands set scan methods #sscan_each when :match supplied when given a block should yield the correct hset elements unchanged
     Failure/Error: expect(results).to match(matching_subset)
       expected ["zeta:two", "zeta:one"] to match ["zeta:one", "zeta:two"]
     # ./spec/redis_spec.rb:685:in `block (7 levels) in <top (required)>'

  4) redis redis 2.8 commands set scan methods #sscan_each when :match supplied without a block should return an Enumerator that yields the correct set elements unchanged
     Failure/Error: expect(enum.to_a).to match(matching_subset)
       expected ["zeta:two", "zeta:one"] to match ["zeta:one", "zeta:two"]
     # ./spec/redis_spec.rb:691:in `block (7 levels) in <top (required)>'

  5) redis redis 2.8 commands set scan methods #sscan_each without :match supplied when given a block should yield all set elements unchanged
     Failure/Error: expect(results).to match(set)
       expected ["three", "zeta:two", "zeta:one"] to match ["zeta:one", "zeta:two", "three"]
     # ./spec/redis_spec.rb:700:in `block (7 levels) in <top (required)>'

  6) redis redis 2.8 commands set scan methods #sscan_each without :match supplied without a block should return an Enumerator that yields all set elements unchanged
     Failure/Error: expect(enum.to_a).to match(set)
       expected ["three", "zeta:two", "zeta:one"] to match ["zeta:one", "zeta:two", "three"]
     # ./spec/redis_spec.rb:706:in `block (7 levels) in <top (required)>'

Finished in 1.41 seconds (files took 0.41109 seconds to load)
96 examples, 6 failures

Failed examples:

rspec ./spec/redis_spec.rb:666 # redis redis 2.8 commands set scan methods #sscan when supplied :match should retrieve the matching set members from the proper set
rspec ./spec/redis_spec.rb:672 # redis redis 2.8 commands set scan methods #sscan without :match supplied should retrieve all set members from the proper set
rspec ./spec/redis_spec.rb:682 # redis redis 2.8 commands set scan methods #sscan_each when :match supplied when given a block should yield the correct hset elements unchanged
rspec ./spec/redis_spec.rb:689 # redis redis 2.8 commands set scan methods #sscan_each when :match supplied without a block should return an Enumerator that yields the correct set elements unchanged
rspec ./spec/redis_spec.rb:697 # redis redis 2.8 commands set scan methods #sscan_each without :match supplied when given a block should yield all set elements unchanged
rspec ./spec/redis_spec.rb:704 # redis redis 2.8 commands set scan methods #sscan_each without :match supplied without a block should return an Enumerator that yields all set elements unchanged

/usr/bin/ruby2.2 /usr/bin/rspec --pattern ./spec/\*\*/\*_spec.rb failed

```

**Comment by balasankarc** [comment]
Sorry. That was a mistake from my part. Sorry for the inconvenience.
