### ISSUE TITLE
Ruby 3.0.0

### ISSUE THREAD

**Issue by Marcellllll** [resque/redis-namespace#178]
Hi,

I am trying to upgrade to Ruby 3.0.0. This gem seems to be limited to Ruby 2.x. Do you think there is a possibility this gem will work with Ruby 3 ?

I don't know how to contribute, but I downloaded the gem, started my redis server, ran the rspec tests with Ruby 3,.0.0 and all tests passed, there were just some warnings:

```
PolarBear:~/Development/redis-namespace$ rspec spec/*
......................................................................Passing 'id' command to redis as is; blind passthrough has been deprecated and will be removed in redis-namespace 2.0 (at /mnt/e/Work/McDevelopment/redis-namespace/spec/redis_spec.rb:482:in `block (4 levels) in <top (required)>')
.Passing 'id' command to redis as is; blind passthrough has been deprecated and will be removed in redis-namespace 2.0 (at /mnt/e/Work/McDevelopment/redis-namespace/spec/redis_spec.rb:491:in `block (4 levels) in <top (required)>')
Passing 'id' command to redis as is; blind passthrough has been deprecated and will be removed in redis-namespace 2.0 (at /mnt/e/Work/McDevelopment/redis-namespace/spec/redis_spec.rb:491:in `block (4 levels) in <top (required)>')
.............................................

Finished in 1.37 seconds (files took 0.22235 seconds to load)
116 examples, 0 failures
```

Kind regards,

**Comment by SamSaffron** [comment]
waiting on a version bump of the gem ... not code needs changing ... just a gem push 

see: 
https://github.com/resque/redis-namespace/commit/c31e63dc3cd5e59ef5ea394d4d46ac60d1e6f82e

**Comment by almostwhitehat** [comment]
👋  Hey @jeremy  - Sorry for the ping, but could we please get a version bump for this?

**Comment by rafaelfranca** [comment]
Done
